[[redirects]]
from = "https://gamedevelop.netlify.app/"
to = "https://gamedevelop.io/"
status = 301
force = true

[[redirects]]
from = "/index.html"
to = "/"
status = 301
force = true

[[redirects]]
from = "/resources.html"
to = "/resources"
status = 301
force = true

[[redirects]]
from = "/about.html"
to = "/about"
status = 301
force = true

[[redirects]]
from = "/404.html"
to = "/404"
status = 301
force = true

[[redirects]]
from = "/guides.html"
to = "/guides"
status = 301
force = true

[[redirects]]
from = "/guides/introductory.html"
to = "/guides/introductory"
status = 301
force = true

[[redirects]]
from = "/guides/introductory/concept.html"
to = "/guides/introductory/concept"
status = 301
force = true

[[redirects]]
from = "/guides/introductory/business.html"
to = "/guides/introductory/business"
status = 301
force = true

[[redirects]]
from = "/guides/introductory/production.html"
to = "/guides/introductory/production"
status = 301
force = true

[[redirects]]
from = "/guides/introductory/tools.html"
to = "/guides/introductory/tools"
status = 301
force = true

[[redirects]]
from = "/guides/introductory/team.html"
to = "/guides/introductory/team"
status = 301
force = true

[[redirects]]
from = "/guides/industry.html"
to = "/guides/industry"
status = 301
force = true

[[redirects]]
from = "/guides/industry/testing.html"
to = "/guides/industry/testing"
status = 301
force = true

[[redirects]]
from = "/guides/industry/overview.html"
to = "/guides/industry/overview"
status = 301
force = true

[[redirects]]
from = "/guides/industry/jobs.html"
to = "/guides/industry/jobs"
status = 301
force = true

[[redirects]]
from = "/guides/industry/culture.html"
to = "/guides/industry/culture"
status = 301
force = true

[[redirects]]
from = "/guides/business-and-marketing.html"
to = "/guides/business-and-marketing"
status = 301
force = true

[[redirects]]
from = "/guides/business-and-marketing/ip.html"
to = "/guides/business-and-marketing/ip"
status = 301
force = true

[[redirects]]
from = "/guides/business-and-marketing/kickstarter.html"
to = "/guides/business-and-marketing/kickstarter"
status = 301
force = true

[[redirects]]
from = "/guides/business-and-marketing/pr.html"
to = "/guides/business-and-marketing/pr"
status = 301
force = true

[[redirects]]
from = "/guides/business-and-marketing/tactics.html"
to = "/guides/business-and-marketing/tactics"
status = 301
force = true

[[redirects]]
from = "/guides/business-and-marketing/youtube.html"
to = "/guides/business-and-marketing/youtube"
status = 301
force = true